# Generated by Django 4.1.4 on 2023-01-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vis',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
